//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos2_wef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int MenuItemID { get; set; }
        public string MenuItemName { get; set; }
        public Nullable<decimal> MenuItemPrice { get; set; }
        public Nullable<bool> MenuItemIsSold { get; set; }
        public string MenuItemCategory { get; set; }
    }
}
