//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos2_wef.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int UserID { get; set; }

        [DisplayName("Username:")]
        [Required(ErrorMessage ="This Field is required.")]
        public string Username { get; set; }

        [DisplayName("Password:")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This Field is required.")]
        public string Password { get; set; }
        public bool IsAdmin { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
